### ISSUE TITLE
CreateVirtualVolumeHosts and DeleteVirtualVolumeHosts 

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/element-software#11]
Page: [Virtual volume API methods](https://docs.netapp.com/us-en/element-software/api/concept_element_api_vvols_api_methods.html)

The API methods DeleteVirtualVolumeHosts and CreateVirtualVolumeHosts are referenced in https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/SolidFire_clusters:_How_to_recover_from_an_ESXi_host_id_change_when_Virtual_Volumes_(VVols)__are_in_use, but I'm not finding them in the user docs.

Are they intended to be internal-only API's, or customer-facing? If the latter, can we please document them in GitHub? If the former, please add explanations as to their function/use in the Internal Notes section of the above KB.

**Comment by netapp-amitha** [comment]
@ddansf The APIs you mention are internal. See here: https://confluence.ngage.netapp.com/display/ELEM/Knowledge+Base+Article+Information
This link is the source of the KB article and it mentions that the APIs are private. Hence, the APIs were included in the "internal" section of the KB.

**Comment by netapp-amitha** [comment]
@ddansf Closing this issue, because we are resolving this offline. Thanks!
