### ISSUE TITLE
Need information on managing multiple VLAN IP block ranges

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/element-software#12]
Page: [Edit a virtual network](https://docs.netapp.com/us-en/element-software/storage/task_system_manage_virtual_edit_a_virtual_network.html)

Customer sometimes need to remove or manage multiple, existing VLAN IP block ranges as well (e.g., to remove a subset of already-provisioned VLAN IP's which include IP's that conflict with other IP's on the network (other Element clusters, compute hosts, etc). We only seem to document how to add an IP block.

**Comment by netapp-dbagwell** [comment]
Hi Dan. Thanks for the feedback. I've created DOC-3468 to address the request.

**Comment by netapp-dbagwell** [comment]
DOC-3468 was completed in June. Sorry, late closing this comment.
