### ISSUE TITLE
add explanation of "enable serial creation" checkbox

### ISSUE THREAD

**Issue by teirhan** [NetAppDocs/element-software#121]
Page: [Create a snapshot schedule](https://docs.netapp.com/us-en/element-software/storage/task_data_protection_create_a_snapshot_schedule.html)

In the snapshot schedule creation wizard, there's a new checkbox added with 12.5 called "Enable Serial Creation" but as best I can tell this was not explained in the 12.5 release notes and is not mentioned here.  A short blurb explaining when this should be checked during schedule creation would be nice.

There is also a new option under snapshot retention called "FIFO (First In First Out)"; and explanation of that was also missing from the patch notes but probably needs to be explained in the public documentation.

**Comment by netapp-pcarriga** [comment]
@teirhan - Thank you for bringing this to our attention.
I'll investigate and update the documentation as soon as possible.
Thank you for helping us improve our customer documentation.

**Comment by netapp-pcarriga** [comment]
@teirhan - Description of "Enable Serial Creation" and "FIFO" have been added to the documentation [here](https://docs.netapp.com/us-en/element-software/storage/task_data_protection_create_a_snapshot_schedule.html).
Thanks again for contacting us and helping us improve our customer documentation.
