### ISSUE TITLE
wrong command

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/element-software#149]
Page: [Install a management node](https://docs.netapp.com/us-en/element-software/mnode/task_mnode_install.html)

/sf/packages/mnode/setup-mnode --mnode_admin_user [username] --storage_mvip [mvip] --storage_username [username] --telemetry_active [true]

should be

sudo /sf/packages/mnode/setup-mnode --mnode_admin_user [username] --storage_mvip [mvip] --storage_username [username] --telemetry_active [true]

**Comment by netapp-pcarriga** [comment]
@ntap-johanneswagner - Hi Johannes, thanks for letting us know about this error. I'll verify the correct command and let you know here when the documentation has been updated.

**Comment by netapp-pcarriga** [comment]
@ntap-johanneswagner - Hi Johannes, the documentation has been updated with your suggestion which you can view here:
[](https://docs.netapp.com/us-en/element-software/mnode/task_mnode_install.html#set-up-the-management-node)
We also made the same change to the "redeploy-mnode" command on the
https://docs.netapp.com/us-en/element-software/mnode/task_mnode_recover.html#configure-the-management-node
