### ISSUE TITLE
HWSB 4.0 Micropatches not available via the element-software docs

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/element-software#15]
Page: [SolidFire and Element Software 12.3 Documentation](https://docs.netapp.com/us-en/element-software/index.html)

While we have major releases linked from the above page, the recent HWSB 4.0 introduced various micropatch releases with newer support for hardware, etc.

The release notes for these are here:

§ Version: 11.8.1 https://mysupport.netapp.com/documentation/docweb/index.html?productID=63944&language=en-US  
§ Version: 12.0.1 https://mysupport.netapp.com/documentation/docweb/index.html?productID=63946&language=en-US  
§ Version: 12.2.1 https://mysupport.netapp.com/documentation/docweb/index.html?productID=63945&language=en-US  

Neither the above site nor https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html have links to the micro patch releases, yet docs.netapp.com seems a likely place to go looking for them rather than mysupport.netapp.com.

Can we add links to the micropatches from the docs.netapp.com content?

**Comment by netapp-amitha** [comment]
@ddansf Thank you for the feedback. Posting micropatch release notes on mysupport has been the traditonal practice, but I agree with you that docs.netapp.com seems like the likely place for users to look for them. The team will discuss this feedback and implement the change. Thanks again!

**Comment by ddansf** [comment]
@netapp-amitha thanks for the quick response! I'm fine if the actual docs are still located on NSS and we just link to them from docs.netapp.com.

**Comment by netapp-amitha** [comment]
https://jira.ngage.netapp.com/browse/DOC-3499 for tracking the fix. @ddansf

**Comment by netapp-amitha** [comment]
@ddansf Updates are live here: https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html
I'm closing this issue. Please reach out if you have further comments. Thanks!
