### ISSUE TITLE
It's unclear what the reader is supposed to see

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#150]
Page: [Perform the prerequisite tasks for installation](https://docs.netapp.com/us-en/element-software/esds/concept_esds_prerequisite_tasks.html)

> Install the supported server. See [NetApp Interoperability Matrix (login required)](https://mysupport.netapp.com/matrix/imt.jsp?components=97283;&solution=1757&isHWU#welcome) for more information.

What is the reader supposed to look for?

**Comment by netapp-barbe** [comment]
Thank you for your question. We will get back to you shortly.

**Comment by netapp-pcarriga** [comment]
Hi @scaleoutsean - I've created DOC-4669 to track this issue.

**Comment by netapp-pcarriga** [comment]
Hi @scaleoutsean - the SolidFire eSDS procedures have been removed from the Element software documentation as the product has reached EOA. Please reach out with any further questions that you may have. Thanks again for your ongoing feedback and helping us improve the SolidFire documentation.
