### ISSUE TITLE
Max QD per iSCSI session was changed from 32 to 128 in 12.7  - req to include this in 12.7 release notes 

### ISSUE THREAD

**Issue by AlvinCrz** [NetAppDocs/element-software#166]
Page: [Current and previous release information](https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html)

I've just found out that Element OS 12.7 now allows 128 QD per iSCSI session, this was not mentioned in the 12.7 release notes.
Can someone update it, as I believe this is a major change. 

Additional Information --> cSCSITaskLimitPerITLNexus is changed to 128 in ELEM-17012.

**Comment by netapp-pcarriga** [comment]
Hi @AlvinCrz, the Element Software Release Notes 12.7 have been update to include the information that each iSCSI session supports a queue depth of 128 iSCSI commands in the "What's new in Element software 12.7" section and under "iSCSI sessions" on page 11:
https://library.netapp.com/ecm/ecm_download_file/ECMLP2884468
