### ISSUE TITLE
Mysterious value in sample output

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#170]
### Page URL

https://docs.netapp.com/us-en/element-software/api/reference_element_api_listsyncjobs.html

### Page title

ListSyncJobs

### Summary

> "totalBytes":200278016remote0,

Is that really how API response values look like?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thank you @scaleoutsean for spotting this issue. I'll verify and update the documentation accordingly.
