### ISSUE TITLE
Wrong format information for bulkVolumeJob array

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#171]
### Page URL

https://docs.netapp.com/us-en/element-software/api/reference_element_api_bulkvolumejob.html

### Page title

bulkVolumeJob

### Summary

This is made up. Native *is* compressed.

![image](https://github.com/NetAppDocs/element-software/assets/16622642/da41862d-9058-4e48-8909-246e1e25cefd)

What's available is native and uncompressed.

![image](https://github.com/NetAppDocs/element-software/assets/16622642/cc573933-6233-4e82-8f3e-c7c010b68335)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thank you @scaleoutsean for spotting this issue. I'll verify and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @scaleoutsean, this error in the bulkVolumeJob topic has been corrected. Thanks again for bringing this to our attention.
