### ISSUE TITLE
You are referencing a private GitHub page

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/element-software#185]
### Page URL

https://docs.netapp.com/us-en/element-software/concepts/concept_rn_whats_new_element.html

### Page title

What’s new in Element software 12.5 and later

### Summary

"To get started, navigate to the [NetApp Ansible repository](https://github.com/NetApp-Automation) on GitHub and download the nar_solidfire_sds_upgrade role and documentation."

![image](https://github.com/NetAppDocs/element-software/assets/20595311/79cc70ce-d7cf-48aa-99d6-3b9deefb2b22)

The page and repository is apparently private.

Either publish the referenced role and documentation (preferably) or remove the reference...

Greetings from Northfriesland

Sebastian

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
@SPGoetze Hi Sebastian, thank you for highlighting this issue. I'll consult with the SolidFire team and make the necessary updates.

**Comment by netapp-pcarriga** [comment]
@SPGoetze The information on Ansible upgrades has been removed from the documentation. Thanks again for bringing this to our attention.
