### ISSUE TITLE
Regarding statement for "iSCSI Sessions" in Element Software 12.7 Release Note.

### ISSUE THREAD

**Issue by hayatokurahashi** [NetAppDocs/element-software#191]
### Page URL

https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html

### Page title

Current and previous release information

### Summary

I suggest to elminate this sentence as it is misleading. Once inernal bugID is opened, I will share more details.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @hayatokurahashi, thank you for your comment. I've opened DOC-4752 to track this request and added you as a watcher. Please provide the details in the comments section. Thanks!
