### ISSUE TITLE
StartBulkVolumeRead fails to apply attributes param values

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#193]
### Page URL

https://docs.netapp.com/us-en/element-software/api/reference_element_api_startbulkvolumeread.html

### Page title

StartBulkVolumeRead

### Summary

The page claims "attributes" can be passed as "JSON attributes for the bulk volume job."

But in reality, that doesn't work. PowerShell example:

```powershell
Invoke-SFApi -Method StartBulkVolumeRead -Params @{ 
   ... 
   "attributes" = @{ 
       "volumeID" = "139"; 
       "volumeName" = "pvc-d793176f-2484-48ea-9255-f70215a7c5f7";
     }
   }
}
```

Attributes got discarded. 

```powershell
PS> Get-SFBulkVolumeJob -VolumeId 139 | ConvertTo-Json -Depth 4       
{                         
  "BulkVolumeID": 101,            
  "CreateTime": "2024-04-24T06:44:32Z",
  "ElapsedTime": 40,
  "Format": "native",               
  "Key": "88d5819d96dfda7190b16a1426fcded0",  
  "PercentComplete": 0,                 
  "RemainingTime": 3960,                                                  
  "SrcVolumeID": 139,       
  "Status": "running",                     
  "Script": "bv_internal.py",
  "SnapshotID": null,    
  "Type": "read",            
  "Attributes": {}                                                 
}   ```
```

Please create a software bug if this is supposed to work, rather than removing `attributes` param from the documentation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by scaleoutsean** [comment]
I just looked again, it doesn't seem those JSON attributes are supposed to be arbitrary.

Since that is the case, it's likely a documentation rather than API bug, and I'd like to ask that allowed attributes and inputs be documented on the page.

**Comment by netapp-pcarriga** [comment]
Thansk @scaleoutsean for bringing this to our attention. I've opened DOC-4756 to track this issue.
