### ISSUE TITLE
CreateVAG and ModifyVAG mention undocumented API parameters

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#26]
> You can also associate a virtual network with a volume access group. 

How? 

The page CreateVolumeAccessGroup and this one (ModifyVolumeAccessGroup) should have these inputs defined, but they don't. 

Page: [ModifyVolumeAccessGroup](https://docs.netapp.com/us-en/element-software/api/reference_element_api_modifyvolumeaccessgroup.html)

**Comment by netapp-dbagwell** [comment]
Thanks @scaleoutsean. Created a doc ticket (DOC-3528) to address this.

**Comment by scaleoutsean** [comment]
By the way - there may be an internal issue for the API based in https://github.com/solidfire/PowerShell/issues/64 but I don't have full visibility so I don't know if something has been already done, but not yet documented.

**Comment by netapp-barbe** [comment]
I've taken a look at PowerShell documentation for 1.6, 1.7, 1.8/12.3 and the commands mentioned are not listed in any of those releases, therefore docs appears to be up to date. 
I don't have access to anything earlier than 1.6

**Comment by scaleoutsean** [comment]
@netapp-barbe , the docs are up to date because the commands aren't mentioned in the PowerShell Tools documentation, but the bug was open because the commands do appear in PowerShell Tools. 

![image](https://user-images.githubusercontent.com/16622642/123898954-dcf17480-d998-11eb-9c35-bb5dc1b76872.png)

I don't know how the parameters got in there, but it's the same question as for our documentation: VAG<=>Network association is mentioned as possible, but it's unclear to me whether it's something that can be done if correct parameters are used, or was never enabled in the API in the first place. The dev in the PowerShell Tools issue said it would be fixed, but not how (by removing the parameters, or by fixing the API).

**Comment by netapp-barbe** [comment]
Sounds good @scaleoutsean; please keep me posted if any documentation changes are required.

**Comment by scaleoutsean** [comment]
@netapp-barbe I learned that my bug report mentioned above has been internally logged as SDK-1153. I don't have access there, but you can follow that issue to determine whether resolution for needs changes to documentation.

I believe it does, i.e. as-is, there's no way to "associate a virtual network with a volume access group". But please check if anyone knows how it can be done, and then expand on that (what part of the HCC or Element UI or API to use to do it).

**Comment by scaleoutsean** [comment]
Has it been determined if this is a documentation (missing details on how to configure this, but the feature is otherwise available) or API (feature not yet implemented) issue?

**Comment by netapp-barbe** [comment]
Looking here: https://jira.ngage.netapp.com/browse/SDK-1153
SDK-1153 is unassigned and still Open.
It links to https://github.com/solidfire/PowerShell/issues/64
Issue 64 includes a conversation between you (scaleoutsean) and Chris Cochran (salmanius).
This also has no one assigned, and is still Open.
There is a comment that salmanius will try to get it into 1.6, but that doesn't seem to have happened.
It also links back to this issue. 

Sean, can you send an email to Chris Cochran, Dave Bagwell, and myself so we can try to get this closed.

**Comment by netapp-barbe** [comment]
Thanks for the clarification (email). A Jira ticket has been created and this GH issue can be closed.
