### ISSUE TITLE
Confusing explanation of Initiator-level CHAP credentials

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#30]
Here it says that "[initiator-level] authentication supersedes account level credentials."

![image](https://user-images.githubusercontent.com/16622642/125892884-c2698d63-2308-4933-a5a6-398ef968afe5.png)

Page: [Work with volume access groups and initiators](https://docs.netapp.com/us-en/element-software/storage/concept_data_manage_vol_access_group_work_with_volume_access_groups_and_initiators.html)

Issues:

1) Instead of "This CHAP level authentication supersedes account level credentials" it should say "This CHAP authentication..."
 or "Initiator-level CHAP authentication...". It's not a CHAP-level authentication, it's one of two CHAP authentication methods supported.

2) I think most dictionaries suggest that "to supersede" means [to replace](https://www.dictionary.com/browse/supersede).

When we say initiator-level CHAP authentication supersedes account-level authentication, I would expect that for VAGs where that IQN is added, account-level authentication should not work (because it's been "superseded" by IQN-specific credentials). But (related to issue #26), that's now what happens - account-level CHAP continues to work for all volumes in the VAG where there are account's volumes and an IQN which "superseded" account-level CHAP. So account-level CHAP doesn't get replaced or obsoleted. 

IQN-level CHAP settings merely create IQN-specific CHAP credentials that are *not tied to any account in any way*. They simply apply to any volume (from any account) in the same VAG where the IQN is. Meanwhile, the storage account(s) owners of those volumes (could be multiple owners, each owns different volumes) could still access their volumes using account-level creds and default SVIP - their account-level CHAP credentials *haven't been superseded* and continue to work independently of IQN-level credentials.

**Comment by netapp-dbagwell** [comment]
Sorry for the response delay on this, Sean. We've created a doc request to address this.

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @scaleoutsean - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - This doc ticket for this issue verifies that the doc changes were published, please refer to DOC-3597, so I'm closing this ticket. If further updates relating to this issue are required, please reopen this issue or start a new issue. 
Thanks!
