### ISSUE TITLE
formatting issue in 'find more information' section

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/element-software#43]
Page: [Configure Fully Qualified Domain Name web UI access](https://docs.netapp.com/us-en/element-software/setup/task_setup_configure_fqdn_web_ui_access.html)

Formatting issue at the end of the page (no anchor text; url's aren't linked):

== Find more information
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]

**Comment by netapp-dbagwell** [comment]
Corrected but never closed this issue. Closing now. Thanks Dan.
