### ISSUE TITLE
Are SIPs used for backup/restore to/from S3

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#44]
Page: [Network port requirements](https://docs.netapp.com/us-en/element-software/storage/reference_prereq_network_port_requirements.html)

In the Network Port Requirements table, under Destination we have S3/Swift endpoint required for both SIP and MIP (each can use one or two destination ports (80, 443)).

Since we can't choose which network to use for backup or restore (in the SF API method), it seems improbable that the both could be used. Route to the specified S3 endpoint would use one (MIP) or the other (SIP) interface, not both.

According to my observations only one network (Management) is used for backup and restore to/from S3. 

Can you confirm which interface (SIP or MIP) is used for S3 backup and restore?

**Comment by netapp-dbagwell** [comment]
Thanks, Sean. Getting clarification. Closing out the GH issue and will track this in a JIRA doc request.

**Comment by scaleoutsean** [comment]
@netapp-dbagwell - okay, thank you, but if it turns that only one (Management *or* Storage) network is used, the list will need fixing because ports 80 and 443 on both networks are currently listed as required.
