### ISSUE TITLE
No download link or information provided, section blank

### ISSUE THREAD

**Issue by wolftales** [NetAppDocs/element-software#45]
Page: [Try storage features using Element Demo Node](https://docs.netapp.com/us-en/element-software/try/task_use_demonode.html)

**Comment by netapp-amitha** [comment]
Hi @wolftales , thanks for the feedback. It sounds like you are looking for a link to download the demo node? I can add the link to the NSS download page.
Is there anything else that is missing? Not sure what you mean by "section blank."

**Comment by netapp-dbagwell** [comment]
Download [link ](https://mysupport.netapp.com/site/tools/tool-eula/element-demonode/download
) added to live content: https://docs.netapp.com/us-en/element-software/try/task_use_demonode.html updated.
