### ISSUE TITLE
Release Notes for 12.3.1

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#50]
Please post a link Release Notes for 12.3.1.

Edit: RN 12.3.1 are at https://library.netapp.com/ecm/ecm_download_file/ECMLP2878089

Page: [Current and previous release information](https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html)

**Comment by netapp-dbagwell** [comment]
There were issues with Element docs publishing this morning. Rn is now live: https://library.netapp.com/ecm/ecm_download_file/ECMLP2878089
Also, GitHub-backed content is live: https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html
