### ISSUE TITLE
Bugs online links are broken links in 12.3.1 release notes

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/element-software#52]
Page: [Current and previous release information](https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html)

On https://library.netapp.com/ecm/ecm_download_file/ECMLP2878089, the bugs referenced in the 12.3.1 release notes are to broken links. For example:https://mysupport.netapp.com/site/bugs-online/product/HCI/JiraNgage/ELEM-16514.

**Comment by netapp-dbagwell** [comment]
@ddansf I've created a ticket to address this: DOC-3734. Closing the GitHub request here and will track progress in JIRA.

**Comment by netapp-amitha** [comment]
@netapp-dbagwell can you assign the ticket to Yvonne if you have not already? She has a couple of 12.3.1 fixes going out in the next day or so. Thanks.

**Comment by netapp-dbagwell** [comment]
Done and done
