### ISSUE TITLE
Update step1 to create a new cluster

### ISSUE THREAD

**Issue by akarwasz** [NetAppDocs/element-software#64]
Page: [Create a storage cluster](https://docs.netapp.com/us-en/element-software/setup/task_setup_create_a_storage_cluster.html)

Change step 1:
"Step 1. In a browser window, enter a node MIP address"

Entering only MIP will bring you to NDE scaler and prompt for password (which doesn't exist)
has to be https://<MIP>:443 or https/:/<MIP>:442/hcc/create-cluster

Please modify step 1 to be: "In a browser window, enter https://MIP:443 where MIP is node management IP address"

**Comment by netapp-pcarriga** [comment]
This documentation is now updated with your recommendation. 
Closing this ticket.
Thanks again!
Paula
