### ISSUE TITLE
Requirements for management interface MTU >=1500 is missing

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#69]
Page: [Considerations for network configuration](https://docs.netapp.com/us-en/element-software/esds/concept_esds_networking_best_practices.html)

MTU on management NIC must be at least 1500. This information is missing.

**Comment by netapp-dbagwell** [comment]
Thanks @scaleoutsean! We'll get this taken care of.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean This missing information on the MTU for the the management NIC as been added to the [Considerations for network configuration ](https://review.docs.netapp.com/us-en/element-software_doc_3985_pc_hotfix_element/esds/concept_esds_networking_best_practices.html).
Thanks again for your feedback.
Closing this issue.
