### ISSUE TITLE
Update docs to reflect the storage node MIP to mnode 443 requirement for upgrades

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/element-software#8]
Page: [Network port requirements](https://docs.netapp.com/us-en/element-software/storage/reference_prereq_network_port_requirements.html)

The storage firmware upgrades initiated by HCC require storage node-->management node MIP connectivity on TCP port 443, whether the cluster is HCI or AFA.

This requirement is missing from https://docs.netapp.com/us-en/element-software/storage/reference_prereq_network_port_requirements.html, but it's present on https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html. Please update the former to include this requirement.

**Comment by netapp-dbagwell** [comment]
Thanks for catching that, Dan. I've created a JIRA doc issue to address this.

**Comment by netapp-dbagwell** [comment]
Closing issue. Addressed in JIRA ticket.
