### ISSUE TITLE
mNode cannot be deployed on a Management Network with DHCP that hands IPs with MTU < 1500

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#83]
```
1. Using the terminal user interface (TUI), create a management node admin user
2. Configure the management node network (eth0)
```

The management node network cannot be configured if there's a DHCP server on the network that hands out IPs with MTU < 1500. 

![image](https://user-images.githubusercontent.com/16622642/157824564-ce18689c-440f-40da-86c1-1b98500d320f.png)

The Web UI won't work either, although the VM has a valid IP address on the correct network (but MTU is < 1500).

This could be documented in a KB or here. Recently I created a suggestion to document minimum MTU requirement for Mgmt Network (which was done), so NDE deployments may avoid this probelm, but anyone re-deploying mNode on a management network with MTU < 1500 later on will hit this problem. 

A workaround - apart from s/w changes to ignore the MTU setting if mNode VM does not have static IP - is to temporarily put mNode on some other vSphere network w/o DHCP (say, iSCSI), reboot the VM (or restart its network), configure correct IP and MTU 1500 (or bigger) on Mgmt Network, and then re-assign the correct VM network to the VM.

Page: [Install a management node](https://docs.netapp.com/us-en/element-software/mnode/task_mnode_install.html)

**Comment by netapp-pcarriga** [comment]
@scaleoutsean  - Thank you for your feedback. I've created [DOC-4094](https://jira.ngage.netapp.com/browse/DOC-4094) to track this documentation update.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean We've updated the documentation with the [instructions for a DHCP gives IPs with an MTU < 1500](https://docs.netapp.com/us-en/element-software/mnode/task_mnode_install.html#create_mnode_admin).
Closing this ticket.
Thanks again!
