### ISSUE TITLE
Work with user accounts

### ISSUE THREAD

**Issue by apordash** [NetAppDocs/element-software#89]
Page: [Work with user accounts](https://docs.netapp.com/us-en/element-software/storage/task_data_manage_accounts_work_with_accounts_task.html)

The opening sentence says this:

In SolidFire storage systems, user accounts enable clients to connect to volumes on a node. When you create a volume, it is assigned to a specific user account.

Make the change to this:

In SolidFire storage systems, user accounts, also known as tenant accounts, enable clients to connect to volumes on a node. When you create a volume, it is assigned to a specific user account.

**Comment by netapp-pcarriga** [comment]
@apordash Thank you for your feedback. I'll verify this change and then update the documentation.

**Comment by netapp-pcarriga** [comment]
@apordash We've incorporated your feedback into the documentation:
https://docs.netapp.com/us-en/element-software/storage/task_data_manage_accounts_work_with_accounts_task.html
Closing this issue.
Thanks again!
