### ISSUE TITLE
Add instructions on how to check the current Maintenance Mode status

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/element-software#9]
Page: [Use maintenance mode on SolidFire eSDS clusters](https://docs.netapp.com/us-en/element-software/esds/reference_esds_use_maintenance_mode.html)

The information on how to find out whether a node is in or out of MaintenanceMode is missing.

**Comment by netapp-amitha** [comment]
@scaleoutsean Hey Sean, this topic includes only the steps to enable/disable maintenance mode. Can you provide some context around the use case where the user would need to check the maintenance mode status?

**Comment by scaleoutsean** [comment]
Hi Amitha, one situation would be to find out whether a node is already disabled. I see the two methods have this info, but if users should use Enable/Disable as he method to find out, then that could be mentioned ("If you want to check if a node ...").

It seems `ListAllNodes` entries have `maintenanceMode` property. That or ListActiveNodes seems like a better way.

**Comment by netapp-amitha** [comment]
@scaleoutsean Added a note in this topic: https://docs.netapp.com/us-en/element-software/esds/reference_esds_use_maintenance_mode.html I'm closing this issue. If you have further comments, please let us know. Thanks!
